on: workflow_dispatch
name: 🚀 Deploy website
env:
  API_KEY: ${{ secrets.API_KEY }}
  FILE_SERVER_HOST: https://kubac.website
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: frodobaggins23/gh-shared-actions/sftp-deploy@main
        with:
          dist-path: dist/kubacovy-hory-ng/browser
          remote-path: hory
          ftp-user: ${{ vars.FTP_USER }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
